In [2]:
import numpy as np


In [ ]:
# Sigmoid activation function
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# Forward propagation
def forward(X, weights):
  z = np.dot(X, weights)  # Linear combination
  return sigmoid(z)       # Apply activation function
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
weights = np.random.randn(2, 1)
output = forward(X, weights)
print("Predicted Output:\n", output)

Predicted Output:
 [[0.5       ]
 [0.19585705]
 [0.6684618 ]
 [0.32934351]]


Compute the loss

In [ ]:
def mean_squared_error(y_true, y_pred):
  return np.mean((y_true - y_pred) ** 2)
# True labels (logical AND function)
y_true = np.array([[0], [0], [0], [1]])

loss = mean_squared_error(y_true, output)
print("Loss:", loss)

Loss: 0.29624532259304637


Backpropogtion

In [ ]:
def sigmoid_derivative(x):
  return x * (1 - x)
# Backpropagation function
def backpropagate(X, y_true, y_pred, weights, learning_rate=0.01):
# Output layer error
  error = y_true - y_pred
# Gradient for output layer (using chain rule)
  d_weights = np.dot(X.T, error * sigmoid_derivative(y_pred))
# Update the weights using the gradients
  weights += d_weights * learning_rate
  return weights
# Perform one step of backpropagation
weights = backpropagate(X, y_true, output, weights) ##

In [ ]:
print(weights)

[[ 0.70123608]
 [-1.41121912]]


train the network

In [ ]:
def train(X, y_true, weights, epochs=10000, learning_rate=0.01):
    for epoch in range(epochs):
        y_pred = forward(X, weights)

        # Backpropagation and weight update
        weights = backpropagate(X, y_true, y_pred, weights, learning_rate)

        # Print loss every 1000 epochs
        if epoch % 100 == 0:
            loss = mean_squared_error(y_true, y_pred)
            print(f'Epoch {epoch}, Loss: {loss}')

    return weights

# Train the network
weights = train(X, y_true, weights)


Epoch 0, Loss: 0.250000177300593
Epoch 100, Loss: 0.25000015646118856
Epoch 200, Loss: 0.2500001380711799
Epoch 300, Loss: 0.2500001218426748
Epoch 400, Loss: 0.2500001075216184
Epoch 500, Loss: 0.25000009488381614
Epoch 600, Loss: 0.25000008373142424
Epoch 700, Loss: 0.2500000738898525
Epoch 800, Loss: 0.25000006520503143
Epoch 900, Loss: 0.2500000575410002
Epoch 1000, Loss: 0.25000005077777837
Epoch 1100, Loss: 0.25000004480948745
Epoch 1200, Loss: 0.25000003954269356
Epoch 1300, Loss: 0.2500000348949448
Epoch 1400, Loss: 0.2500000307934804
Epoch 1500, Loss: 0.2500000271740915
Epoch 1600, Loss: 0.2500000239801163
Epoch 1700, Loss: 0.25000002116155284
Epoch 1800, Loss: 0.2500000186742761
Epoch 1900, Loss: 0.2500000164793478
Epoch 2000, Loss: 0.25000001454240567
Epoch 2100, Loss: 0.25000001283312695
Epoch 2200, Loss: 0.25000001132475264
Epoch 2300, Loss: 0.2500000099936689
Epoch 2400, Loss: 0.25000000881903744
Epoch 2500, Loss: 0.25000000778246934
Epoch 2600, Loss: 0.2500000068677368
E

In [ ]:

# Test the trained network
final_output = forward(X, weights)
print("Final Predicted Output:\n", final_output)

Final Predicted Output:
 [[0.5       ]
 [0.49999885]
 [0.50000115]
 [0.5       ]]


experiement

In [5]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of sigmoid function
def sigmoid_derivative(x):
    return x * (1 - x)

# Mean Squared Error (MSE) Loss function
def mean_squared_error(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Forward propagation
def forward(X, weights, bias):
    z = np.dot(X, weights) + bias
    return sigmoid(z)

# Backpropagation function
def backpropagate(X, y_true, y_pred, weights, bias, learning_rate=0.01):
    # Output layer error
    error = y_true - y_pred

    # Gradient for weights and bias (using chain rule)
    d_weights = np.dot(X.T, error * sigmoid_derivative(y_pred))
    d_bias = np.sum(error * sigmoid_derivative(y_pred), axis=0, keepdims=True)

    # Update the weights and bias using the gradients
    weights += d_weights * learning_rate
    bias += d_bias * learning_rate

    return weights, bias

# Training function
def train(X, y_true, weights, bias, epochs=10000, learning_rate=0.01):
    for epoch in range(epochs):
        # Forward propagation
        y_pred = forward(X, weights, bias)

        # Backpropagation and weight update
        weights, bias = backpropagate(X, y_true, y_pred, weights, bias, learning_rate)

        # Print loss every 1000 epochs
        if epoch % 1000 == 0:
            loss = mean_squared_error(y_true, y_pred)
            print(f'Epoch {epoch}, Loss: {loss}')

    return weights, bias

# Main function
if __name__ == "__main__":
    # Input data (X) and true output (y_true)
    X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Logical AND inputs
    y_true = np.array([[0], [0], [0], [1]])         # Logical AND outputs

    # Initialize weights and bias
    weights = np.random.randn(2, 1)  # Random weights (2 inputs to 1 output)
    bias = np.random.randn(1, 1)     # Random bias

    print("Initial Weights:\n", weights)
    print("Initial Bias:\n", bias)

    # Train the network
    trained_weights, trained_bias = train(X, y_true, weights, bias)

    # Test the trained network
    final_output = forward(X, trained_weights, trained_bias)
    print("Final Predicted Output:\n", final_output)

    # Experiment with hyperparameters
    print("\nExperimenting with learning rate:")
    trained_weights_lr, trained_bias_lr = train(X, y_true, weights, bias, learning_rate=0.1)
    final_output_lr = forward(X, trained_weights_lr, trained_bias_lr)
    print("Final Predicted Output with higher learning rate:\n", final_output_lr)


Initial Weights:
 [[ 1.02659149]
 [-0.66995925]]
Initial Bias:
 [[0.39375643]]
Epoch 0, Loss: 0.32356366615928667
Epoch 1000, Loss: 0.1559169530920663
Epoch 2000, Loss: 0.10982602248630877
Epoch 3000, Loss: 0.08565490491815281
Epoch 4000, Loss: 0.07042669701248712
Epoch 5000, Loss: 0.059679142988282446
Epoch 6000, Loss: 0.05159787206945214
Epoch 7000, Loss: 0.0452825740592855
Epoch 8000, Loss: 0.040215417140710294
Epoch 9000, Loss: 0.036068359799585586
Final Predicted Output:
 [[0.01737299]
 [0.19286138]
 [0.19360847]
 [0.76441832]]

Experimenting with learning rate:
Epoch 0, Loss: 0.032620075416857366
Epoch 1000, Loss: 0.015893651278124275
Epoch 2000, Loss: 0.010152368642912104
Epoch 3000, Loss: 0.0073562499463891585
Epoch 4000, Loss: 0.005727879842854609
Epoch 5000, Loss: 0.00467097253553545
Epoch 6000, Loss: 0.003933300478012456
Epoch 7000, Loss: 0.0033909682903290415
Epoch 8000, Loss: 0.0029763888167747823
Epoch 9000, Loss: 0.0026497093166353344
Final Predicted Output with higher l